export const CLEAR_NODES = 'CLEAR_NODES';
export const SET_ELEMENTS = 'SET_ELEMENTS';
export const SET_ERROR = 'SET_ERROR';

export const FETCH_DETAILS = 'FETCH_DETAILS';
export const FETCH_SEARCH_RESULTS_AND = 'FETCH_SEARCH_RESULTS_AND';
export const FETCH_SEARCH_RESULTS_OR = 'FETCH_SEARCH_RESULTS_OR';


export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';