export const CLEAR_NODES = "CLEAR_NODES";
export const SET_ELEMENTS = "SET_ELEMENTS";
export const SET_ERROR = "SET_ERROR";

export const FETCH_DETAILS = "FETCH_DETAILS";

export const OPEN_CONTEXT_MENU = "OPEN_CONTEXT_MENU";
export const CLOSE_CONTEXT_MENU = "CLOSE_CONTEXT_MENU";

export const OPEN_ERROR_MODAL = "OPEN_ERROR_MODAL";
export const CLOSE_ERROR_MODAL = "CLOSE_ERROR_MODAL";

export const OPEN_LOADING_SCREEN = "OPEN_LOADING_SCREEN";
export const CLOSE_LOADING_SCREEN = "CLOSE_LOADING_SCREEN";
